version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: minimal

configuration:
  - Release

test_script:
- cmd: >-
    %APPVEYOR_BUILD_FOLDER%\VisualStudio\x64\%configuration%\test_rand.exe

    %APPVEYOR_BUILD_FOLDER%\VisualStudio\x64\%configuration%\test_kex.exe
